# Generated by Django 2.0.3 on 2018-04-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deleted_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_entry', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Short_url_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='url_mapping',
            fields=[
                ('short_url', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=200)),
                ('ttl', models.IntegerField()),
                ('added', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='short_url_info',
            name='short_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_url.url_mapping'),
        ),
    ]
