# Generated by Django 2.0.3 on 2018-04-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_auto_20180417_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_stats',
            name='short_url',
        ),
        migrations.DeleteModel(
            name='url_stats',
        ),
    ]
