# Generated by Django 2.0.3 on 2018-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0003_auto_20180418_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='url_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=8)),
                ('browser', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('hit_time', models.IntegerField()),
            ],
        ),
    ]
